### ISSUE TITLE
[TODO] Lavaproof Sword

### ISSUE THREAD

**Issue by ToMe25** [ToMe25/Botania-Additions#4]
Works basically like the Terra Blade, but does a bit more damage, and is lava resistant.
It might get a completely new texture and maybe some other small changes.

**Comment by kuroyure** [comment]
if you allow the suggestion this could be instead a terra blade, using the original terraria terra blade texture and size relative to the player (making it a gigantic sword the size of steve's body) with a similar attack speed, instead of simply coating it with netherite, crafting a broken hero sword using gaia spirits ender air and  a netherite sword, it of course would not be able to be burned and rename the botania terra blade as terrasteel sword since thats more its vibe than the actual terra blade

**Comment by ToMe25** [comment]
Imo giant swords never really look good in mc, and i also don't like just stealing the texture from terraria.
I might make it a new sword instead, tho that would mean having to make a texture for it, which i am not good at, just making a netherite version of an existing item would be easier.
Also i think making a sword as expensive as that would require it to be pretty strong to be worth that, which would kinda make it op.
If this would become its own sword, instead of just a netherite coated version of the Terra Blade, it would be a bit more expensive then the Starcaller and Thundercaller, but not that much, as to only making it a bit worse prise/performace wise, without making it op.

**Comment by kuroyure** [comment]
"making it op" is relative because on the gaia tier botania has such things as the key of the king's law and the ring of odin, so buffing its dammage to 9 and making its attack speed a tad quicker wouldnt make it broken by botania standards, and after figthing gaia 2 gaia spirits are abundant to the point of the player having too many to spend after getting all the relics, besides the starcaller is a direct rip of the terraria sword, and thats ok, because its a reference, about the size, if converted to minecraft it would only be the size of an ice and fire sword(and lots of ppl love them), maybe a bit longer, so it wouldnt look too bad, the most change one would need to do is change the handle to livingwood and making it thinner

**Comment by kuroyure** [comment]
besides making "the terrablade but coated in netherite" is kinda uninteresting and does not fit botania, as it tends to add more steps than simple coat this weapon in this next tier material

**Comment by ToMe25** [comment]
True, botania usually doesn't add recipes like that, however minecraft usually doesn't either, however it does for netherite.

**Comment by kuroyure** [comment]
i think in the netherite case mojang wanted to add a use for the upgrading table but they wanted to keep it simple and dumb so they just made netherite a pain to get and made only 1 ingot necessary to get netherite gear + using the broken hero sword on an upgrade table with a terrasteel sword is totaly an option, in fact it makes more sense if that and all the fluguel tiara recipes were upgrade table recipes tbh

**Comment by ToMe25** [comment]
I might add Homing Mana Bursts on swing, somewhat like the [Holy Sword Excalibur](https://ftb.gamepedia.com/Holy_Sword_Excaliber) had, back when that was a thing.
Or maybe not, not sure how i want this sword to look and what name it should get.
If this feature fits the look and name i will add it, if not i wont.

**Comment by ToMe25** [comment]
Closing this since Terrasteel tools are fire proof now.
They are fire proof since quite a while actually, I just forgot about this issue.
This issue does suggest other differences between the normal sword and the new one, but since the main point was it being fire proof I'm closing this.
